#
# PROGRAM: Reading virtual /proc files
# AUTHOR: Cortland Ervins
#

CXXFLAGS = -ansi -pedantic -Wall -Werror -Wextra -std=c++14

main: main.o
	g++ $(CXXFLAGS) -c -o main.o main.cpp
	g++ $(CXXFLAGS) -o z1813736_project1 main.o
    
clean:
	rm -f *.o main z1813736_project1
